import { useState, useEffect } from 'react';

const Landing = () => {
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Initialize page
    console.log('Landing mounted');
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4 py-8">
        <header className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white">
            Landing
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            Page generated by AI Agent
          </p>
        </header>

        <main className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
          <div className="space-y-6">
            <section>
              <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-200 mb-4">
                Welcome
              </h2>
              <p className="text-gray-600 dark:text-gray-300">
                This is your Landing page. Start customizing it!
              </p>
            </section>

            <section className="pt-6 border-t border-gray-200 dark:border-gray-700">
              <button
                onClick={() => setLoading(!loading)}
                className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                {loading ? 'Loading...' : 'Get Started'}
              </button>
            </section>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Landing;
